# Generated by Django 2.1.5 on 2019-02-25 17:02

import Test.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='InputTextFile',
            field=models.FileField(upload_to=Test.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
