# Generated by Django 2.1.5 on 2019-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20190225_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='Uploader_info',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
