# Generated by Django 2.1.5 on 2019-03-01 14:54

import Test.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0003_testinfo_uploader_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testinfos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='InputTextFile',
            field=models.FileField(upload_to=Test.models.content_file_name, validators=[Test.models.validate_file_extension]),
        ),
    ]
