# Generated by Django 2.1.7 on 2019-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20190301_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
