# Generated by Django 2.1.7 on 2019-03-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_testinfo_pathvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='pathValue',
        ),
    ]
