# Generated by Django 2.1.5 on 2019-02-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestMaking', '0002_remove_quesmodel_ques'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
